config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  get '/complete/:id', to: 'tasks#complete', as: 'complete'
  get '/incomplete/:id', to: 'tasks#incomplete', as: 'incomplete'
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

  scope :complete, -> { where(complete: true) }
  scope :incomplete, -> { where(complete: false) }

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def mark_complete!
    self.update_attribute(:complete, true)
  end

  def mark_incomplete!
    self.update_attribute(:complete, false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!

  respond_to :html
  respond_to :js

  def index
    if current_user
      @user = current_user
    else
      @user = User.first
    end
    @tasks = @user.tasks.all
    respond_with(@tasks)
  end

  def complete
    @task = Task.find(params[:id])
    if @task.complete
      redirect_to action: 'incomplete'
    else
      @task.mark_complete!
    end
  end

  def incomplete
    @task = Task.find(params[:id])
    @task.mark_incomplete!
  end

  def new
    if current_user
      @user = current_user
    else
      @user = User.first
    end
    @task = Task.new
    respond_with(@task)
  end

  def edit
    if current_user
      @user = current_user
    else
      @user = User.first
    end
  end

  def create
    if current_user
      @user = current_user
    else
      @user = User.first
    end
    @task = Task.new(task_params)
    @task.save
    respond_with(@task)
  end

  def update
    if current_user
      @user = current_user
    else
      @user = User.first
    end
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :complete, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnePageTodoAjax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <% flash.each do | name, msg |%>
        <%= content_tag(:div, msg, class:"alert alert-info") %>
      <% end %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, label: false, placeholder: "Task Name", autocomplete: "off", class: 'form-control' %>
  </div>

  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= div_for(task, class: "col-md-4 col-sm-4 col-xs-6 box ") do %>
  <div class="inside-box">
    <h3 class="task-name"><%= task.name %></h3>

    <ul class="action-box">
     <li><%= link_to "Edit Task", edit_task_path(task), remote: true %></li>
     <li><%= link_to task.complete ? "Mark Incomplete" : "Mark Complete", complete_path(task), remote: true %></li>
     <li><%= link_to "Delete Task", task, remote: true, method: :delete %></li>
    </ul>
  </div>
<% end %>

app/views/tasks/complete.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();
$('.completed-tasks').append('<%= j render partial: "task", locals: {task: @task} %>');
$('div#<%= dom_id(@task) %>').find('h3').css('text-decoration', 'line-through');

app/views/tasks/create.js.erb
$('form').hide();
$('.my-tasks').append('<%= j render partial: "task", locals: {task: @task} %>');
$('.new-task-button').show();

app/views/tasks/destroy.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();

app/views/tasks/edit.js.erb
$('form').hide();
$('.new-task-button').replaceWith('<%= j render("form") %>');
$('div#<%= dom_id(@task) %>').replaceWith('<%= j render partial: "task", locals: {task: @task} %>');

app/views/tasks/incomplete.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();
$('.my-tasks').append('<%= j render partial: "task", locals: {task: @task} %>');
$('div#<%= dom_id(@task) %>').find('h3').css('text-decoration', 'none');

app/views/tasks/index.html.erb
<div class="logo row">
  <div class="image logo-content">
  <%= image_tag "todo.png" %>
  </div>
  <div class="logo-title logo-content">
    <span class="center">Your own <br> ToDo list</span>
  </div>
</div>
</ul>
<div class="clear"></div>
<h3 class="title">Completed Tasks</h3>
<div class="completed-tasks row">
    <% @tasks.complete.each do |task| %>
      <%= render task %>
    <% end %>
</div>

<h3 class="title">Incompleted Tasks</h3>
<div class="my-tasks row">
  <% @tasks.incomplete.each do |task| %>
    <%= render task %>
  <% end %>
</div>
<div class="fotter-button">
  <div class="new-button-place">
    <%= link_to 'New Task', new_task_path, remote: true, class: 'new-task-button' %>
  </div>
  <div class="devise-button">
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_user_registration_path, class: 'button right' %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'button right' %>
  <% else %>
    <%= link_to 'Log in', new_user_session_path, class: 'button'  %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'button'  %>
  <% end %>
  </div>
</div>

app/views/tasks/new.js.erb
$('.new-task-button').after('<%= j render('form') %>');
$('.new-task-button').hide();

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('form').hide();
$('div#<%= dom_id(@task) %>').replaceWith('<%= j render partial: "task", locals: {task: @task} %>');
$('.new-button-place').append('<%= link_to 'New Task', new_task_path, remote: true, class: 'new-task-button' %>');